M48
; DRILL file {KiCad 8.0.9} date 2025-06-18T23:52:02+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-18T23:52:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X5.0181Y-1.8701
X5.2181Y-1.8701
T2
X5.1075Y-2.5787
X5.2075Y-2.5787
M30
